// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
	"github.com/minskylab/life/example/ent/autor"
	"github.com/minskylab/life/example/ent/todo"
)

// AutorCreate is the builder for creating a Autor entity.
type AutorCreate struct {
	config
	mutation *AutorMutation
	hooks    []Hook
}

// SetName sets the name field.
func (ac *AutorCreate) SetName(s string) *AutorCreate {
	ac.mutation.SetName(s)
	return ac
}

// SetSignature sets the signature field.
func (ac *AutorCreate) SetSignature(s string) *AutorCreate {
	ac.mutation.SetSignature(s)
	return ac
}

// SetNillableSignature sets the signature field if the given value is not nil.
func (ac *AutorCreate) SetNillableSignature(s *string) *AutorCreate {
	if s != nil {
		ac.SetSignature(*s)
	}
	return ac
}

// SetID sets the id field.
func (ac *AutorCreate) SetID(s string) *AutorCreate {
	ac.mutation.SetID(s)
	return ac
}

// AddTodoIDs adds the todos edge to Todo by ids.
func (ac *AutorCreate) AddTodoIDs(ids ...string) *AutorCreate {
	ac.mutation.AddTodoIDs(ids...)
	return ac
}

// AddTodos adds the todos edges to Todo.
func (ac *AutorCreate) AddTodos(t ...*Todo) *AutorCreate {
	ids := make([]string, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddTodoIDs(ids...)
}

// Mutation returns the AutorMutation object of the builder.
func (ac *AutorCreate) Mutation() *AutorMutation {
	return ac.mutation
}

// Save creates the Autor in the database.
func (ac *AutorCreate) Save(ctx context.Context) (*Autor, error) {
	var (
		err  error
		node *Autor
	)
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AutorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			node, err = ac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AutorCreate) SaveX(ctx context.Context) *Autor {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (ac *AutorCreate) check() error {
	if _, ok := ac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := ac.mutation.ID(); ok {
		if err := autor.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf("ent: validator failed for field \"id\": %w", err)}
		}
	}
	if len(ac.mutation.TodosIDs()) == 0 {
		return &ValidationError{Name: "todos", err: errors.New("ent: missing required edge \"todos\"")}
	}
	return nil
}

func (ac *AutorCreate) sqlSave(ctx context.Context) (*Autor, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}

func (ac *AutorCreate) createSpec() (*Autor, *sqlgraph.CreateSpec) {
	var (
		_node = &Autor{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: autor.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: autor.FieldID,
			},
		}
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: autor.FieldName,
		})
		_node.Name = value
	}
	if value, ok := ac.mutation.Signature(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: autor.FieldSignature,
		})
		_node.Signature = value
	}
	if nodes := ac.mutation.TodosIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   autor.TodosTable,
			Columns: []string{autor.TodosColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: todo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AutorCreateBulk is the builder for creating a bulk of Autor entities.
type AutorCreateBulk struct {
	config
	builders []*AutorCreate
}

// Save creates the Autor entities in the database.
func (acb *AutorCreateBulk) Save(ctx context.Context) ([]*Autor, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Autor, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AutorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (acb *AutorCreateBulk) SaveX(ctx context.Context) []*Autor {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
