// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Autor is the predicate function for autor builders.
type Autor func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
